hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("waybar & hyprpaper")
    hl.exec_cmd("swayidle -w")
    hl.exec_cmd("nwg-look -a")

    hl.exec_cmd("firefox", { workspace = "1 silent" })
end)
